/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2019 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
// int puts(const char *s);
// int printf(const char *format, ...);
// char *fgets(char *s, int n, FILE *stream);
// int execve(const char *path, char *const argv[], char *const envp[]);
// int __fastcall _cxa_finalize(void *);
// void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>);
__int64 (**deregister_tm_clones())(void);
__int64 register_tm_clones();
__int64 (**_do_global_dtors_aux())(void);
__int64 __fastcall frame_dummy(_QWORD, _QWORD, _QWORD); // weak
int win();
int lose1();
int lose2();
int lose3();
int lose4();
int no_panic();
int close_borders();
int play_game();
int __cdecl main(int argc, const char **argv, const char **envp);
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3);
void _libc_csu_fini(void); // idb
void term_proc();
// int __fastcall _libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int __fastcall __cxa_finalize(void *);
// __int64 ITM_deregisterTMCloneTable(void); weak
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

__int64 (__fastcall *_frame_dummy_init_array_entry)() = &frame_dummy; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
void *_dso_handle = &_dso_handle; // idb
FILE *_bss_start; // idb
char completed_7963; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    result = (__int64 (**)(void))_gmon_start__();
  return result;
}
// 4060: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0LL);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001080) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(__int64 a1@<rax>, void (*a2)(void)@<rdx>)
{
  int v2; // esi
  __int64 v3; // [rsp-8h] [rbp-8h]
  char *retaddr; // [rsp+0h] [rbp+0h]

  v2 = v3;
  v3 = a1;
  _libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    v2,
    &retaddr,
    (void (*)(void))_libc_csu_init,
    _libc_csu_fini,
    a2,
    &v3);
  __halt();
}
// 1086: positive sp value 8 has been found

//----- (00000000000010B0) ----------------------------------------------------
__int64 (**deregister_tm_clones())(void)
{
  __int64 (**result)(void); // rax

  result = (__int64 (**)(void))&_bss_start;
  if ( &_bss_start != &_bss_start )
  {
    result = &ITM_deregisterTMCloneTable;
    if ( &ITM_deregisterTMCloneTable )
      result = (__int64 (**)(void))ITM_deregisterTMCloneTable();
  }
  return result;
}
// 4058: using guessed type __int64 ITM_deregisterTMCloneTable(void);

//----- (00000000000010E0) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}

//----- (0000000000001120) ----------------------------------------------------
__int64 (**_do_global_dtors_aux())(void)
{
  __int64 (**result)(void); // rax

  if ( !completed_7963 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    completed_7963 = 1;
  }
  return result;
}
// 4018: using guessed type char completed_7963;

//----- (0000000000001165) ----------------------------------------------------
int win()
{
  char *argv; // [rsp+0h] [rbp-20h]
  const char *v2; // [rsp+8h] [rbp-18h]
  __int64 v3; // [rsp+10h] [rbp-10h]

  printf("I'm not sure how, but your terrible leadership worked!");
  argv = "/bin/cat";
  v2 = "flag.txt";
  v3 = 0LL;
  return execve("/bin/cat", &argv, 0LL);
}

//----- (00000000000011B7) ----------------------------------------------------
int lose1()
{
  puts("\nYour test comes back negative, but no one trusts your doctor.");
  return puts("The country goes into mass hysteria and society collapses.");
}

//----- (00000000000011D6) ----------------------------------------------------
int lose2()
{
  puts("\nThe Christian community praises your good sense while buying up all the toilet paper in the country.");
  return puts("As the shelves run dry and society collapses.");
}

//----- (00000000000011F5) ----------------------------------------------------
int lose3()
{
  puts("\nHospitals become overrun with cases and many people without healthcare can't afford treatment");
  return puts("Society collapses as hospitals fill.");
}

//----- (0000000000001214) ----------------------------------------------------
int lose4()
{
  puts("\nNo one under the age of 50 cares about the emergency and bars have their best weekend in months.");
  return puts("The virus rapidly spreads and society collapses.");
}

//----- (0000000000001233) ----------------------------------------------------
int no_panic()
{
  int result; // eax
  char s[64]; // [rsp+0h] [rbp-40h]

  puts("\nExcellent choice. It's all a hoax anyway!");
  puts("Oof WHO just announced it's a pandemic AND American treasure Thomas Hanks is quarentined...");
  puts("1. Get tested and show everyone your immune system is the best. Just the greatest");
  puts("2. Call for a national day of prayer. God will save us!");
  fgets(s, 50, _bss_start);
  printf("You chose: ");
  printf(s);
  if ( s[0] == 49 )
    return lose1();
  result = 50 - (unsigned __int8)s[0];
  if ( s[0] == 50 )
    result = lose2();
  return result;
}

//----- (00000000000012F0) ----------------------------------------------------
int close_borders()
{
  int result; // eax
  char s[64]; // [rsp+0h] [rbp-40h]

  puts("\nSo we closed our borders. Weren't we doing that anyway with the wall?");
  puts("It's still spreading within our borders what do we do now?");
  puts("1. Reassure everyone the country can handle this. Our healthcare system is the best. Just the greatest.");
  puts("2. Make it a national emergency. Show the people we don't need Bernie's healthcare plan.");
  fgets(s, 50, _bss_start);
  printf("You chose: ");
  printf(s);
  if ( s[0] == 49 )
    return lose3();
  result = 50 - (unsigned __int8)s[0];
  if ( s[0] == 50 )
    result = lose4();
  return result;
}

//----- (00000000000013AD) ----------------------------------------------------
int play_game()
{
  int result; // eax
  char s[64]; // [rsp+0h] [rbp-40h]

  puts("Welcome to this choose your own adventure game!");
  puts("You're President Ronald Drump and are tasked with leading the nation through this crisis.");
  puts("So what do you want to do?");
  puts("1. Close the borders.");
  puts("2. Tell everyone not to panic. It's just the Fake News media freaking out.");
  fgets(s, 50, _bss_start);
  printf("You chose: ");
  printf(s);
  if ( s[0] == 49 )
    return close_borders();
  result = 50 - (unsigned __int8)s[0];
  if ( s[0] == 50 )
    result = no_panic();
  return result;
}

//----- (0000000000001476) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  play_game();
  return 0;
}

//----- (0000000000001490) ----------------------------------------------------
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3)
{
  signed __int64 v4; // rbp
  __int64 i; // rbx

  init_proc();
  v4 = &_do_global_dtors_aux_fini_array_entry - &_frame_dummy_init_array_entry;
  if ( v4 )
  {
    for ( i = 0LL; i != v4; ++i )
      ((void (__fastcall *)(_QWORD, __int64, __int64))*(&_frame_dummy_init_array_entry + i))(a1, a2, a3);
  }
}
// 1160: using guessed type __int64 __fastcall frame_dummy(_QWORD, _QWORD, _QWORD);
// 3DA0: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry)();
// 3DA8: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (00000000000014F4) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=31 queued=17 decompiled=17 lumina nreq=0 worse=0 better=0
// ALL OK, 17 function(s) have been successfully decompiled
