/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2019 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
// ssize_t read(int fd, void *buf, size_t nbytes);
// int printf(const char *format, ...);
// int getchar(void);
// __sighandler_t signal(int sig, __sighandler_t handler);
// unsigned int alarm(unsigned int seconds);
// int __cdecl __cxa_finalize(void *);
// int puts(const char *s);
// int system(const char *command);
int __gmon_start__(void); // weak
// void exit(int status);
// int __cdecl __libc_start_main(int (__cdecl *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// int sprintf(char *s, const char *format, ...);
// int __cdecl __isoc99_scanf(_DWORD, _DWORD); weak
// void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>);
void sub_6C2();
void _x86_get_pc_thunk_bx();
void *deregister_tm_clones();
int register_tm_clones();
void *_do_global_dtors_aux();
int frame_dummy();
void _x86_get_pc_thunk_dx();
void __noreturn handler(); // weak
char *setup();
int _();
unsigned int vuln();
int win();
int __cdecl main(int argc, const char **argv, const char **envp);
void *_x86_get_pc_thunk_ax();
int (**_libc_csu_init())();
int _libc_csu_fini(); // weak
void term_proc();
// int __cdecl _cxa_finalize(void *);

//-------------------------------------------------------------------------
// Data declarations

char byte_B7B[10] = { '\xF0', '\x9F', '\x92', '\xA9', ' ', ' ', ' ', '%', 's', '\0' }; // idb
int (*_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
int (*_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
_DWORD _JCR_LIST__ = 0; // idb
void *_dso_handle = &_dso_handle; // weak
_UNKNOWN _bss_start; // weak
_UNKNOWN unk_200B; // weak
char completed_7176; // weak
char cmd[80]; // idb
_UNKNOWN flag; // weak
// extern _UNKNOWN IO_2_1_stdin_; weak
// extern _UNKNOWN IO_2_1_stdout_; weak
// extern _UNKNOWN ITM_deregisterTMCloneTable; weak
// extern _UNKNOWN _gmon_start__; weak
// extern _UNKNOWN Jv_RegisterClasses; weak


//----- (000005D0) --------------------------------------------------------
void *init_proc()
{
  void *result; // eax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    result = (void *)__gmon_start__();
  return result;
}
// 658: using guessed type int __gmon_start__(void);

//----- (00000690) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>)
{
  int v2; // esi
  int v3; // [esp-4h] [ebp-4h]
  char *retaddr; // [esp+0h] [ebp+0h]

  v2 = v3;
  v3 = a1;
  __libc_start_main(
    (int (__cdecl *)(int, char **, char **))main,
    v2,
    &retaddr,
    (void (*)(void))_libc_csu_init,
    (void (*)(void))_libc_csu_fini,
    a2,
    &v3);
  __halt();
}
// 693: positive sp value 4 has been found
// AF0: using guessed type int _libc_csu_fini();

//----- (000006C2) --------------------------------------------------------
void sub_6C2()
{
  ;
}

//----- (000006D0) --------------------------------------------------------
void _x86_get_pc_thunk_bx()
{
  ;
}

//----- (000006E0) --------------------------------------------------------
void *deregister_tm_clones()
{
  void *result; // eax

  result = (void *)(&unk_200B - &_bss_start);
  if ( (unsigned int)(&unk_200B - &_bss_start) > 6 )
  {
    result = &ITM_deregisterTMCloneTable;
    if ( &ITM_deregisterTMCloneTable )
      result = (void *)((int (__cdecl *)(void *))ITM_deregisterTMCloneTable)(&_bss_start);
  }
  return result;
}
// 6E0: could not find valid save-restore pair for ebp

//----- (00000720) --------------------------------------------------------
int register_tm_clones()
{
  return 0;
}
// 720: could not find valid save-restore pair for ebp

//----- (00000770) --------------------------------------------------------
void *_do_global_dtors_aux()
{
  void *result; // eax

  if ( !completed_7176 )
  {
    if ( &_cxa_finalize )
      __cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    completed_7176 = 1;
  }
  return result;
}
// 2004: using guessed type void *_dso_handle;
// 2020: using guessed type char completed_7176;

//----- (000007C0) --------------------------------------------------------
int frame_dummy()
{
  if ( _JCR_LIST__ && &Jv_RegisterClasses )
    ((void (__cdecl *)(_DWORD *))Jv_RegisterClasses)(&_JCR_LIST__);
  return register_tm_clones();
}
// 7C0: could not find valid save-restore pair for ebp

//----- (000007FC) --------------------------------------------------------
void _x86_get_pc_thunk_dx()
{
  ;
}

//----- (00000800) --------------------------------------------------------
void __noreturn handler()
{
  exit(1);
}
// 800: using guessed type void __noreturn handler();

//----- (0000081D) --------------------------------------------------------
char *setup()
{
  char *result; // eax

  setvbuf((FILE *)&IO_2_1_stdout_, 0, 2, 0);
  setvbuf((FILE *)&IO_2_1_stdin_, 0, 2, 0);
  signal(14, (__sighandler_t)handler);
  alarm(0x3Cu);
  result = cmd;
  strcpy(&cmd[32], "Menu:\n");
  return result;
}
// 800: using guessed type void __noreturn handler();

//----- (00000897) --------------------------------------------------------
int _()
{
  int result; // eax

  result = 8096;
  if ( *flag )
    result = system("cat flag");
  return result;
}

//----- (000008D2) --------------------------------------------------------
unsigned int vuln()
{
  int v1; // [esp+8h] [ebp-10h]
  unsigned int v2; // [esp+Ch] [ebp-Ch]

  v2 = __readgsdword(0x14u);
  while ( 1 )
  {
    while ( 1 )
    {
      printf(&cmd[32]);
      puts("1. Edit name.\n2. Prep msg.\n3. Print msg.\n4. Exit.");
      printf("> ");
      __isoc99_scanf("%d", &v1);
      getchar();
      if ( (unsigned __int8)v1 != 1 )
        break;
      printf("Name: ");
      read(0, &cmd[48], 0x1Fu);
    }
    if ( (int)(unsigned __int8)v1 <= 1 )
      break;
    if ( (unsigned __int8)v1 == 2 )
    {
      sprintf(cmd, byte_B7B, &cmd[48]);
    }
    else if ( (unsigned __int8)v1 == 3 )
    {
      puts(cmd);
    }
    else
    {
LABEL_12:
      puts("Invalid");
    }
  }
  if ( (_BYTE)v1 )
    goto LABEL_12;
  return __readgsdword(0x14u) ^ v2;
}
// 680: using guessed type int __cdecl __isoc99_scanf(_DWORD, _DWORD);

//----- (000009FD) --------------------------------------------------------
int win()
{
  return system("cat flag");
}

//----- (00000A28) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  setup();
  printf("Name: ");
  read(0, &cmd[48], 0x1Fu);
  vuln();
  return 0;
}

//----- (00000A86) --------------------------------------------------------
void *_x86_get_pc_thunk_ax()
{
  void *retaddr; // [esp+0h] [ebp+0h]

  return retaddr;
}

//----- (00000A90) --------------------------------------------------------
int (**_libc_csu_init())()
{
  int (**result)(); // eax
  int v1; // esi
  int i; // edi

  init_proc();
  result = _frame_dummy_init_array_entry;
  v1 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  if ( v1 )
  {
    for ( i = 0; i != v1; ++i )
      result = (int (**)())_frame_dummy_init_array_entry[i]();
  }
  return result;
}
// 1EB4: using guessed type int (*_frame_dummy_init_array_entry[2])();
// 1EB8: using guessed type int (*_do_global_dtors_aux_fini_array_entry)();

//----- (00000B14) --------------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=49 queued=18 decompiled=18 lumina nreq=0 worse=0 better=0
// ALL OK, 18 function(s) have been successfully decompiled
